version: '3.3'
services:

  postgres:
    image: postgres:13
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:


